import * as stylex from '@stylexjs/stylex';
import { colors, layout } from '../tokens.stylex.js';

// Strong ease-out (starts fast → responsive entrances). Matches the auth card.
const EASE_OUT = 'cubic-bezier(.23,1,.32,1)';
const CORAL = '#E96D4F';
const BLUE = '#4E9EDB';
const REDUCE = '@media (prefers-reduced-motion: reduce)';
const NARROW = '@media (max-width: 760px)';
const TIGHT = '@media (max-width: 460px)';

// One shared rise-in keyframe; each element sets its own animationDelay inline
// so the hero staggers in. Nothing appears from nothing — we fade + lift, never
// scale from zero.
const rise = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(12px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
});

const floatY = stylex.keyframes({
  '0%, 100%': { transform: 'translateY(0)' },
  '50%': { transform: 'translateY(-6px)' },
});

export const landing = stylex.create({
  page: {
    minHeight: '100dvh',
    color: colors.ink,
    fontFamily: layout.font,
    // Soft twin-accent wash, anchored top corners — same hues as the auth mark,
    // faint enough to survive both themes.
    backgroundColor: colors.bg,
    backgroundImage: `radial-gradient(1100px 560px at 8% -8%, color-mix(in srgb, ${CORAL} 13%, transparent), transparent 58%), radial-gradient(900px 520px at 100% -4%, color-mix(in srgb, ${BLUE} 12%, transparent), transparent 55%)`,
    backgroundRepeat: 'no-repeat',
    overflowX: 'hidden',
    // Korean line-breaking: break between words (eojeol), never mid-word.
    wordBreak: 'keep-all',
  },

  // ── Nav ────────────────────────────────────────────────────────────────
  // Full-bleed sticky band; frosts + grows a hairline border once scrolled.
  navBand: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    backgroundColor: 'transparent',
    transitionProperty: 'background-color, border-color',
    transitionDuration: '220ms',
    transitionTimingFunction: 'ease',
  },
  navScrolled: {
    backgroundColor: colors.glass,
    borderBottomColor: colors.line,
    backdropFilter: 'saturate(1.4) blur(12px)',
    WebkitBackdropFilter: 'saturate(1.4) blur(12px)',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    height: '60px',
    paddingInline: 'clamp(16px, 5vw, 40px)',
    maxWidth: '1080px',
    marginInline: 'auto',
  },
  brand: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '9px',
    fontSize: '14.5px',
    fontWeight: 640,
    letterSpacing: '-0.015em',
    color: colors.ink,
  },
  navRight: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },

  // Brand mark — the two-tone tile from the auth screen, reused for continuity.
  mark: {
    width: '26px',
    height: '26px',
    borderRadius: '8px',
    backgroundColor: colors.ink,
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '2.5px',
    padding: '6px',
    flexShrink: 0,
  },
  markLg: {
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    padding: '9px',
    gap: '3.5px',
  },
  markA: {
    borderRadius: '2.5px',
    backgroundColor: CORAL,
    alignSelf: 'end',
    height: '9px',
  },
  markB: {
    borderRadius: '2.5px',
    backgroundColor: BLUE,
    alignSelf: 'start',
    height: '8px',
  },

  // ── Layout shell ───────────────────────────────────────────────────────
  shell: {
    maxWidth: '1080px',
    marginInline: 'auto',
    paddingInline: 'clamp(16px, 5vw, 40px)',
  },

  // ── Hero ───────────────────────────────────────────────────────────────
  hero: {
    display: 'grid',
    gridTemplateColumns: '1.05fr 0.95fr',
    gap: 'clamp(28px, 5vw, 64px)',
    alignItems: 'center',
    paddingTop: 'clamp(48px, 9vw, 104px)',
    paddingBottom: 'clamp(48px, 8vw, 92px)',
    [NARROW]: {
      gridTemplateColumns: '1fr',
      gap: '40px',
      paddingTop: '40px',
    },
  },
  heroCopy: {
    maxWidth: '38ch',
    [NARROW]: { maxWidth: 'none' },
  },
  eyebrow: {
    display: 'inline-block',
    color: colors.muted,
    fontSize: '13px',
    fontWeight: 560,
    letterSpacing: '0.002em',
    marginBottom: '18px',
  },
  h1: {
    margin: 0,
    fontSize: 'clamp(38px, 6.4vw, 64px)',
    lineHeight: 1.04,
    letterSpacing: '-0.035em',
    fontWeight: 720,
    color: colors.ink,
    textWrap: 'balance',
  },
  h1Accent: {
    // Gradient ink for the second line — coral→blue, the product's two hues.
    backgroundImage: `linear-gradient(105deg, ${CORAL}, ${BLUE})`,
    WebkitBackgroundClip: 'text',
    backgroundClip: 'text',
    color: 'transparent',
    WebkitTextFillColor: 'transparent',
  },
  lede: {
    marginTop: '20px',
    marginBottom: 0,
    fontSize: 'clamp(15px, 1.7vw, 17.5px)',
    lineHeight: 1.6,
    color: colors.muted,
    textWrap: 'pretty',
  },
  ctaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '10px',
    marginTop: '30px',
  },
  ctaNote: {
    marginTop: '16px',
    fontSize: '12.5px',
    lineHeight: 1.5,
    color: colors.faint,
    textWrap: 'pretty',
  },

  // ── Buttons ────────────────────────────────────────────────────────────
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    height: '46px',
    paddingInline: '20px',
    borderWidth: 0,
    borderRadius: '12px',
    fontSize: '14.5px',
    fontWeight: 600,
    letterSpacing: '-0.006em',
    fontFamily: 'inherit',
    cursor: 'pointer',
    userSelect: 'none',
    touchAction: 'manipulation',
    whiteSpace: 'nowrap',
    transitionProperty: 'transform, box-shadow, background-color, color, opacity',
    transitionDuration: '160ms',
    transitionTimingFunction: EASE_OUT,
    ':active': { transform: 'scale(0.97)' },
    ':disabled': { opacity: 0.55, cursor: 'default', transform: 'none' },
    [REDUCE]: { transitionDuration: '0ms' },
  },
  btnPrimary: {
    backgroundColor: colors.ink,
    color: colors.onInk,
    boxShadow: '0 1px 2px rgba(20,20,26,.16), 0 10px 24px -12px rgba(20,20,26,.5)',
    ':hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 2px 6px rgba(20,20,26,.2), 0 16px 32px -12px rgba(20,20,26,.55)',
    },
    // :hover lift + :active press share the transform channel — press wins.
    ':active': { transform: 'scale(0.97)' },
  },
  btnGhost: {
    backgroundColor: colors.paper,
    color: colors.ink,
    boxShadow: `inset 0 0 0 1px ${colors.edge}`,
    ':hover': { boxShadow: `inset 0 0 0 1px ${colors.edgeH}`, backgroundColor: colors.paper },
  },
  btnArrow: {
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: EASE_OUT,
  },
  spinner: {
    width: '15px',
    height: '15px',
    borderRadius: '99px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: 'currentColor',
    borderTopColor: 'transparent',
    animationName: stylex.keyframes({ to: { transform: 'rotate(360deg)' } }),
    animationDuration: '640ms',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
    opacity: 0.9,
  },

  // Small icon button (theme toggle) — matches the app's ibtn feel.
  iconBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderWidth: 0,
    borderRadius: '10px',
    backgroundColor: 'transparent',
    color: colors.muted,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transitionProperty: 'background-color, color, transform',
    transitionDuration: '150ms',
    transitionTimingFunction: 'ease',
    ':hover': { backgroundColor: colors.hov, color: colors.ink },
    ':active': { transform: 'scale(0.94)' },
  },
  navLink: {
    height: '36px',
    paddingInline: '14px',
    borderRadius: '10px',
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: '13.5px',
    fontWeight: 560,
    color: colors.muted,
    backgroundColor: 'transparent',
    borderWidth: 0,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transitionProperty: 'background-color, color',
    transitionDuration: '150ms',
    transitionTimingFunction: 'ease',
    ':hover': { backgroundColor: colors.hov, color: colors.ink },
  },

  // ── Hero preview card (mini planner) ──────────────────────────────────
  previewWrap: {
    position: 'relative',
    perspective: '1200px',
    [NARROW]: { order: -1 },
  },
  // A faithful mini of the real planner grid — same header rail, weekday cells,
  // today pill, hour lines, event blocks and now-line as the app.
  preview: {
    borderRadius: '14px',
    backgroundColor: colors.paper,
    border: `1px solid ${colors.line}`,
    boxShadow: `0 2px 6px rgba(20,20,26,.05), 0 40px 80px -40px rgba(20,20,26,.4)`,
    overflow: 'hidden',
    animationName: floatY,
    animationDuration: '7s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    [REDUCE]: { animationName: 'none' },
  },
  // Header rail: 시간 corner + weekday cells, mirrors grid.headClip.
  pHead: {
    display: 'grid',
    gridTemplateColumns: '38px repeat(5, 1fr)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.line,
  },
  pCorner: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    padding: '0 6px 5px',
    fontSize: '8.5px',
    fontWeight: 550,
    letterSpacing: '0.02em',
    color: colors.faint,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: colors.line,
  },
  pDay: {
    height: '38px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: colors.line,
  },
  pDko: { fontSize: '11.5px', fontWeight: 600, lineHeight: 1, color: colors.ink },
  pToday: {
    width: '19px',
    height: '19px',
    borderRadius: '99px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.ink,
    color: colors.onInk,
    fontSize: '10.5px',
  },
  pDen: { fontSize: '8.5px', fontWeight: 500, color: colors.faint, letterSpacing: '0.012em' },
  pBody: {
    display: 'grid',
    gridTemplateColumns: '38px repeat(5, 1fr)',
  },
  pGut: {
    position: 'relative',
    height: '200px',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: colors.line,
  },
  pTime: {
    position: 'absolute',
    right: '6px',
    transform: 'translateY(-50%)',
    fontSize: '8.5px',
    fontWeight: 500,
    lineHeight: 1,
    color: colors.faint,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: '0.012em',
  },
  pCol: {
    position: 'relative',
    height: '200px',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: colors.line,
  },
  pLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: '1px',
    backgroundColor: colors.gridHour,
  },
  pBlock: {
    position: 'absolute',
    left: '3px',
    right: '3px',
    borderRadius: '6px',
    padding: '4px 6px 4px 10px',
    backgroundColor: 'var(--ev-bg)',
    color: 'var(--ev-fg)',
    overflow: 'hidden',
    boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--ev-accent) 22%, transparent)',
    // Rounded accent rail on the left — same detail as grid.blk::before.
    '::before': {
      content: '""',
      position: 'absolute',
      left: '3px',
      top: '3px',
      bottom: '3px',
      width: '2.5px',
      borderRadius: '99px',
      backgroundColor: 'var(--ev-accent)',
    },
  },
  pBt: {
    fontSize: '9.5px',
    fontWeight: 600,
    lineHeight: 1.25,
    letterSpacing: '-0.006em',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  pBm: {
    marginTop: '1px',
    fontSize: '8px',
    fontWeight: 500,
    opacity: 0.72,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: '0.012em',
  },
  pNow: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: '2px',
    borderRadius: '2px',
    backgroundColor: colors.now,
    boxShadow: `0 0 0 1px ${colors.nowHalo}`,
    zIndex: 6,
    '::before': {
      content: '""',
      position: 'absolute',
      left: '-2px',
      top: '-2px',
      width: '6px',
      height: '6px',
      borderRadius: '99px',
      backgroundColor: colors.now,
      boxShadow: `0 0 0 1.5px ${colors.nowHalo}`,
    },
  },
  // Floating presence avatars over the preview — hints at real-time collab.
  presence: {
    position: 'absolute',
    top: '10px',
    right: '12px',
    zIndex: 10,
    display: 'inline-flex',
    paddingBlock: '5px',
    paddingInline: '9px 11px',
    borderRadius: '99px',
    backgroundColor: colors.paper,
    boxShadow: `0 0 0 1px ${colors.edge}, 0 10px 24px -12px rgba(20,20,26,.4)`,
    alignItems: 'center',
    gap: '7px',
    [TIGHT]: { display: 'none' },
  },
  avatars: { display: 'inline-flex' },
  avatar: {
    width: '20px',
    height: '20px',
    borderRadius: '99px',
    marginLeft: '-6px',
    boxShadow: `0 0 0 2px ${colors.paper}`,
    display: 'grid',
    placeItems: 'center',
    fontSize: '9px',
    fontWeight: 700,
    color: '#fff',
  },
  presenceTxt: { fontSize: '10.5px', fontWeight: 560, color: colors.muted },

  // ── Section scaffolding ────────────────────────────────────────────────
  section: {
    paddingBlock: 'clamp(56px, 9vw, 104px)',
  },
  sectionHead: {
    maxWidth: '640px',
    marginBottom: 'clamp(32px, 5vw, 52px)',
  },
  kicker: {
    fontSize: '12.5px',
    fontWeight: 640,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: CORAL,
    marginBottom: '12px',
  },
  h2: {
    margin: 0,
    fontSize: 'clamp(26px, 4vw, 38px)',
    lineHeight: 1.1,
    letterSpacing: '-0.028em',
    fontWeight: 680,
    color: colors.ink,
    textWrap: 'balance',
  },
  sectionSub: {
    marginTop: '16px',
    marginBottom: 0,
    fontSize: 'clamp(14.5px, 1.6vw, 16px)',
    lineHeight: 1.6,
    color: colors.muted,
    textWrap: 'pretty',
  },

  // ── Feature grid ───────────────────────────────────────────────────────
  features: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '14px',
    [NARROW]: { gridTemplateColumns: 'repeat(2, 1fr)' },
    [TIGHT]: { gridTemplateColumns: '1fr' },
  },
  card: {
    position: 'relative',
    padding: '22px 20px 24px',
    borderRadius: '16px',
    backgroundColor: colors.paper,
    boxShadow: `inset 0 0 0 1px ${colors.edge}`,
    transitionProperty: 'transform, box-shadow',
    transitionDuration: '220ms',
    transitionTimingFunction: EASE_OUT,
    ':hover': {
      transform: 'translateY(-3px)',
      boxShadow: `inset 0 0 0 1px ${colors.edgeH}, 0 2px 4px rgba(20,20,26,.04), 0 18px 36px -20px rgba(20,20,26,.32)`,
    },
    [REDUCE]: { transitionDuration: '0ms', ':hover': { transform: 'none' } },
  },
  cardIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    height: '38px',
    borderRadius: '11px',
    marginBottom: '15px',
    color: colors.ink,
    backgroundColor: colors.field,
    boxShadow: `inset 0 0 0 1px ${colors.edge}`,
  },
  cardTitle: {
    margin: 0,
    fontSize: '15.5px',
    fontWeight: 640,
    letterSpacing: '-0.012em',
    color: colors.ink,
  },
  cardBody: {
    marginTop: '7px',
    marginBottom: 0,
    fontSize: '13.5px',
    lineHeight: 1.58,
    color: colors.muted,
    textWrap: 'pretty',
  },

  // ── Guest spotlight ────────────────────────────────────────────────────
  guest: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '22px',
    paddingBlock: 'clamp(40px, 6vw, 60px)',
    paddingInline: 'clamp(24px, 5vw, 56px)',
    backgroundColor: colors.paper,
    boxShadow: `inset 0 0 0 1px ${colors.edge}`,
    backgroundImage: `radial-gradient(720px 300px at 88% -20%, color-mix(in srgb, ${BLUE} 14%, transparent), transparent 60%), radial-gradient(560px 260px at 4% 120%, color-mix(in srgb, ${CORAL} 12%, transparent), transparent 62%)`,
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    gap: 'clamp(28px, 5vw, 56px)',
    alignItems: 'center',
    [NARROW]: { gridTemplateColumns: '1fr' },
  },
  guestCopy: { maxWidth: '46ch' },
  guestSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: '236px',
    margin: 0,
    padding: 0,
    listStyle: 'none',
    [NARROW]: { minWidth: 0 },
  },
  step: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '13px',
    padding: '12px 4px',
  },
  stepNum: {
    flexShrink: 0,
    width: '26px',
    height: '26px',
    borderRadius: '99px',
    display: 'grid',
    placeItems: 'center',
    fontSize: '12px',
    fontWeight: 680,
    fontVariantNumeric: 'tabular-nums',
    color: colors.onInk,
    backgroundColor: colors.ink,
  },
  stepTitle: {
    fontSize: '13.5px',
    fontWeight: 620,
    color: colors.ink,
    letterSpacing: '-0.008em',
  },
  stepBody: {
    marginTop: '2px',
    fontSize: '12.5px',
    lineHeight: 1.5,
    color: colors.muted,
    textWrap: 'pretty',
  },
  stepConnector: {
    width: '1.5px',
    height: '10px',
    marginLeft: '17px',
    backgroundColor: colors.line,
  },
  guestCta: { marginTop: '28px', display: 'flex', flexWrap: 'wrap', gap: '10px' },

  // ── Footer ─────────────────────────────────────────────────────────────
  footer: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.line,
    marginTop: 'clamp(40px, 6vw, 72px)',
  },
  footerInner: {
    maxWidth: '1080px',
    marginInline: 'auto',
    paddingInline: 'clamp(16px, 5vw, 40px)',
    paddingBlock: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    flexWrap: 'wrap',
  },
  footerTxt: { fontSize: '12.5px', color: colors.faint, fontWeight: 500 },

  // ── Entrance stagger ───────────────────────────────────────────────────
  rise: {
    animationName: rise,
    animationDuration: '640ms',
    animationTimingFunction: EASE_OUT,
    animationFillMode: 'both',
    [REDUCE]: { animationName: 'none' },
  },
});
