import * as stylex from '@stylexjs/stylex';
import { colors, layout } from '../tokens.stylex.js';

export const reset = stylex.create({
  html: {
    height: '100%',
    colorScheme: 'light dark',
  },
  body: {
    margin: 0,
    height: '100%',
    backgroundColor: colors.bg,
    color: colors.ink,
    fontFamily: layout.font,
    fontSize: '14px',
    lineHeight: 1.45,
    WebkitFontSmoothing: 'antialiased',
    textRendering: 'optimizeLegibility',
    WebkitTextSizeAdjust: '100%',
    WebkitTapHighlightColor: 'transparent',
    transitionProperty: 'background-color',
    transitionDuration: '200ms',
    transitionTimingFunction: 'ease',
  },
  app: {
    height: '100%',
  },
  boot: {
    minHeight: '100dvh',
    display: 'grid',
    placeItems: 'center',
    color: colors.muted,
    fontSize: '13px',
    fontWeight: 500,
  },
});

export const ui = stylex.create({
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: '9px',
    paddingBlock: '7px',
    paddingInline: '12px',
    fontSize: '12.5px',
    fontWeight: 560,
    letterSpacing: '-0.002em',
    color: colors.ink,
    cursor: 'pointer',
    userSelect: 'none',
    touchAction: 'manipulation',
    fontFamily: 'inherit',
    transitionProperty: 'background-color, box-shadow, transform, color, opacity',
    transitionDuration: '150ms',
    transitionTimingFunction: 'ease',
    ':active': { transform: 'scale(0.96)' },
    ':disabled': {
      opacity: 0.4,
      cursor: 'not-allowed',
      transform: 'none',
      pointerEvents: 'none',
    },
  },
  btnPrimary: {
    backgroundColor: colors.ink,
    color: colors.onInk,
    ':hover': { opacity: 0.92 },
  },
  btnPlain: {
    backgroundColor: colors.paper,
    color: colors.muted,
    boxShadow: `inset 0 0 0 1px ${colors.edge}, 0 1px 2px rgba(27,27,32,.05)`,
    ':hover': {
      color: colors.ink,
      boxShadow: `inset 0 0 0 1px ${colors.edgeH}, 0 1px 2px rgba(27,27,32,.06)`,
    },
  },
  btnGhost: {
    backgroundColor: 'transparent',
    color: colors.muted,
    ':hover': { backgroundColor: colors.hov },
  },
  btnDanger: {
    backgroundColor: 'transparent',
    color: colors.now,
    ':hover': { backgroundColor: 'rgba(229,72,77,.10)' },
  },
  ibtn: {
    flexShrink: 0,
    width: '31px',
    height: '31px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    borderRadius: '9px',
    backgroundColor: colors.paper,
    color: colors.muted,
    cursor: 'pointer',
    boxShadow: `inset 0 0 0 1px ${colors.edge}, 0 1px 2px rgba(27,27,32,.05)`,
    transitionProperty: 'color, box-shadow, transform',
    transitionDuration: '150ms',
    ':hover': {
      color: colors.ink,
      boxShadow: `inset 0 0 0 1px ${colors.edgeH}, 0 1px 2px rgba(27,27,32,.06)`,
    },
    ':active': { transform: 'scale(0.94)' },
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    borderWidth: 0,
    borderRadius: '10px',
    paddingBlock: '10px',
    paddingInline: '12px',
    backgroundColor: colors.field,
    color: colors.ink,
    fontSize: '14px',
    fontFamily: 'inherit',
    outline: 'none',
    ':focus': {
      boxShadow: `0 0 0 2px ${colors.paper}, 0 0 0 4px ${colors.ink}`,
    },
    ':disabled': { opacity: 0.55 },
  },
  inputSm: {
    paddingBlock: '7px',
    paddingInline: '10px',
    fontSize: '12.5px',
    borderRadius: '8px',
    fontVariantNumeric: 'tabular-nums',
  },
});
